services:
  aarvantage:
    build: >-
      https://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@github.com/Kazwahs/arrvantage.git
    container_name: aarvantage
    environment:
      - CONFIG_DIR=/app/data
      - FORCE_HTTPS_COOKIES=false
    ports:
      - '30099:5000'
    restart: unless-stopped
    volumes:
      - /mnt/NasWahs1/appdata/arrvantage:/app/data


TMDB API: a914f50a4067fba2efbcc990079ed1a7